src/Entity/Canal.php
<?php

namespace App\Entity;

use App\Repository\CanalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CanalRepository::class)]
class Canal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\OneToOne(targetEntity: User::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private $Author;

    #[ORM\Column(type: 'string', length: 255)]
    private $Nombre;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Descripcion;

    #[ORM\Column(type: 'float')]
    private $precio;

    #[ORM\OneToMany(mappedBy: 'canal', targetEntity: Reserva::class, orphanRemoval: true)]
    private $reservas;

    public function __construct()
    {
        $this->reservas = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId(User $Id): self
    {
        $this->id = $Id;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(?string $Descripcion): self
    {
        $this->Descripcion = $Descripcion;

        return $this;
    }

    public function getPrecio(): ?int
    {
        return $this->precio;
    }

    public function setPrecio(int $precio): self
    {
        $this->precio = $precio;

        return $this;
    }

    /**
     * @return Collection|Reserva[]
     */
    public function getReservas(): Collection
    {
        return $this->reservas;
    }

    public function addReserva(Reserva $reserva): self
    {
        if (!$this->reservas->contains($reserva)) {
            $this->reservas[] = $reserva;
            $reserva->setCanal($this);
        }

        return $this;
    }

    public function removeReserva(Reserva $reserva): self
    {
        if ($this->reservas->removeElement($reserva)) {
            // set the owning side to null (unless already changed)
            if ($reserva->getCanal() === $this) {
                $reserva->setCanal(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->Author;
    }

}

templates/canales/canales.html.twig
{% for canal in canales %}
          <div class="col-lg-4 col-md-6 portfolio-item filter-web">
            <div class="portfolio-wrap">
          {% if canal.foto == "" %}
                <img src="{{asset('img2/profiler/noprofile.jpg')}}" class="img h-100 w-100 " alt="noprofile">
              {% else %}
                <img src="{{asset('img2/profiler/' ~ canal.foto)}}" class="img h-100 w-100" alt={{canal.foto}}>

          {% endif %}
              <div class="portfolio-info">
                <h4>{{canal.nombre}}</h4>
                <p>{{canal.username}}</p>
                <div class="portfolio-links">
                  <a href="{{asset('img/portfolio/portfolio-9.jpg')}}" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Web 3"><i class="fa fa-eye"></i></a>
                </div>
              </div>
            </div>
          </div>
    {% endfor %}

templates/canales/canalesCabecera.html.twig
<section id="portfolio" class="portfolio">
    <div class="container">

        <div class="section-title aos-init aos-animate" data-aos="fade-up">
          <h2>Canales</h2>
          <p>Encuentra a tus creadores de contenidos favoritos, aquí en StromZu.com</p>
        </div>

        <div class="row aos-init aos-animate" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-12 d-flex justify-content-center">
            <ul id="portfolio-flters">
            <li>
              <button id="vueltaInicio" class="btn btn-outline-success h-100" type="submit">Volver a inicio</button>
            </li>
              <li data-filter="*" class="filter-active">
                <input id="buscador" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
              </li>
            </ul>
          </div>
        </div>



        <div id="bloqueCanales" class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">
    
        </div>
    </div>
</section>  